name: Labeler

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labeler.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
