name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/p/python-jmap
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Bump version for release release
        run: |
          version=${GITHUB_REF#refs/*/}
          poetry version $version

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.7
